---
title: "Dependent Stress-Strength Reliability Model with Modified Weibull Distribution Marginals via Clayton Copula"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dependent Stress-Strength Reliability Model

For a $2$-dimensional continuous random vector $\mathbf{X}=(X,Y)$ with joint cumulative distribution function (cdf) $H(x,y)$ and univariate marginal cdfs $F(x)$ and $G(y)$. Then, based on Sklar's Theorem there exist a unique $2$-dimensional copula function $C:[0,1]^2 \rightarrow [0,1]$ satisfying 
$$
    H(\mathbf{x})=C \big( F(x), G(y) \big).
$$
Let $c$ and $h$ be the corresponding joint probability density function (pdf) of $C$ and $H$, respectively, and $f,g$ are the corresponding pdf of $F, G$, we have
$$
  h(x,y) = \frac{\partial H(x,y)}{\partial x \partial y} = \frac{\partial C(F(x), G(y))}{\partial x \partial y} = c \big( F(x), G(y) \big) f(x) g(y).
 $$

Let the strength $X$ and stress $Y$ variables be dependent, with their dependence modeled via a two-dimensional copula function $C(u,v)$ and joint pdf $h(x,y)$. Then, the dependent stress–strength reliability $R$ is given by 
$$
  \begin{eqnarray*}
    R = P(X>Y) &=& \int_{0}^{\infty} \int_{0}^{x} h(x,y) \mathrm{d}y \mathrm{d}x 
    = \int_{0}^{\infty} \int_{0}^{x} \frac{\partial C^2(u,v)}{\partial u \partial v} \Biggr|_{ \begin{smallmatrix} u=F(x) \\ v = G(y) \end{smallmatrix} } f(x) g(y) \mathrm{d}y \mathrm{d}x \notag \\  
    &=& \int_{0}^{\infty}  \frac{\partial C(u,v)}{\partial u} \Biggr|_{ \begin{smallmatrix} u=F(x) \\ v = G(x) \end{smallmatrix} } f_X(x) \mathrm{d}x.
\end{eqnarray*}
$$

The joint distribution function of the two-dimensional Clayton copula, along with its joint probability density function, are given by
$$C_{\theta}(u,v) = (u^{-\theta} + v^{-\theta} - 1)^{-1/\theta},$$
and
$$c_{\theta}(u,v) = (\theta +1)  u^{-(\theta + 1)} v^{-(\theta + 1)} \big( u^{-\theta} + v^{-\theta}-1 \big)^{-\left (\frac{1}{\theta} + 2 \right)}$$,
where $\theta >0$. 

When $X \sim MWD(a_1,b_1,\lambda_1)$, $Y \sim MWD(a_2,b_2,\lambda_2)$ with the two-dimensional Clayton copula from, $R$ becomes 
$$
\begin{eqnarray}
    R &=& \int_{0}^{\infty}  F_X(x)^{-(\theta + 1)} \big(F_X(x)^{-\theta} + G_Y(x)^{-\theta}-1 \big) ^{-\left (\frac{1}{\theta}+1 \right)} f_X(x) \mathrm{d}x \notag \\
    &=& \int_{0}^{1} t^{-(\theta +1)} \big( t^{-\theta} + G_Y(F_{X}^{-1}(t))^{-\theta} -1 \big)^ {-\left(\frac{1}{\theta}+1 \right) } \mathrm{d}t, 
\end{eqnarray}
$$
where $F_X(x) \equiv F_X(x;a_1,b_1,\lambda_1)  = 1- \exp(-a_1 x^{b_1} e^{\lambda_1 x})$ and $G_Y(y) \equiv G_Y(y;a_2,b_2,\lambda_2) = 1- \exp(-a_2 y^{b_2} e^{\lambda_2 y})$.

Further details can be found in [Kızılaslan (2026)](https://arxiv.org/abs/????).

## References

Kızılaslan, Fatih. (2026). *Reliability estimation in dependent stress–strength model with Clayton copula and modified Weibull margins.*[arXiv:26????](https://arxiv.org/abs/????)
